# 配置端口
server:
  port: 51102

#swagger:
#  enable: true

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    com.tj.id.mapper: DEBUG  # 针对 Mapper 接口包开启 DEBUG 日志
    org.apache.ibatis: DEBUG
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 到控制台
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl  # 打印 SQL 到控制台
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 打印 SQL 到控制台

spring:
#  profiles:
#    active: dev
  #    active: sit
  #    active: uat
  #    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/id_generator?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin1104

crypto:
  apiPublicKey: d22743ba937765c3df1808cffdce82d67b76f987f7acf188bd7bc6dd39277d9c
  apiPrivateKey: REMOVED_SECRET
  proxy:
    host: 127.0.0.1
    port: 10808
  websocket:
    baseUrl: wss://fstream.binance.com
#    baseUrl: https://testnet.binancefuture.com
    websocketUrl: wss://fstream.binance.com/ws/btcusdt@kline_1m
#    websocketUrl: wss://fstream.binancefuture.com/ws/btcusdt@kline_1m

