CREATE TABLE backtest_run (
    run_id VARCHAR(64) PRIMARY KEY,
    strategy_name VARCHAR(100) NOT NULL,
    exchange VARCHAR(20) NOT NULL,
    market_type VARCHAR(20) NOT NULL,
    symbol VARCHAR(40) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    data_start_time BIGINT NOT NULL,
    start_time BIGINT NOT NULL,
    end_time BIGINT NOT NULL,
    initial_capital DECIMAL(38,18) NOT NULL,
    final_capital DECIMAL(38,18) NOT NULL,
    total_return_pct DECIMAL(24,12) NOT NULL,
    max_drawdown_pct DECIMAL(24,12) NOT NULL,
    win_rate_pct DECIMAL(24,12) NOT NULL,
    sharpe_ratio DECIMAL(24,12) NOT NULL,
    total_trades INT NOT NULL,
    winning_trades INT NOT NULL,
    losing_trades INT NOT NULL,
    avg_win DECIMAL(38,18) NOT NULL,
    avg_loss DECIMAL(38,18) NOT NULL,
    profit_factor DECIMAL(24,12) NOT NULL,
    total_fees DECIMAL(38,18) NOT NULL,
    assumptions_json JSON NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_backtest_strategy_time (strategy_name, create_time),
    INDEX idx_backtest_instrument_time (exchange, market_type, symbol, timeframe, create_time)
) ENGINE=InnoDB COMMENT='回测运行摘要与可复现假设';

CREATE TABLE backtest_trade (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    sequence_no INT NOT NULL,
    side VARCHAR(8) NOT NULL,
    quantity DECIMAL(38,18) NOT NULL,
    entry_price DECIMAL(38,18) NOT NULL,
    exit_price DECIMAL(38,18) NOT NULL,
    entry_time BIGINT NOT NULL,
    exit_time BIGINT NOT NULL,
    realized_pnl DECIMAL(38,18) NOT NULL,
    total_fee DECIMAL(38,18) NOT NULL,
    net_pnl DECIMAL(38,18) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_backtest_trade_sequence (run_id, sequence_no),
    INDEX idx_backtest_trade_exit (run_id, exit_time)
) ENGINE=InnoDB COMMENT='回测逐笔交易';
